check-update: false
gui: false
commit: false
dirty-commits: false
auto-commits: false
show-model-warnings: false
# model: "ollama/llama3:70b"
model: "ollama/llama3:8b"
openai-api-base: "https://ollama.mobile.ifi.lmu.de"
pretty: false
show-repo-map: true
verbose: true
show-diffs: true
# dry-run: true
